### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by kwestlund** [mzaks/FlatBuffersSwift#3]
java.lang.NullPointerException
    at maxim.zaks.generator.EagerSwiftGenerator.generate(EagerSwiftGenerator.java:38)
    at maxim.zaks.Main.run(Main.java:89)
    at maxim.zaks.Main.main(Main.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

**Comment by kwestlund** [comment]
It turns out this is caused by a flatbuffers schema file without a root_type specified.

**Comment by mzaks** [comment]
Thanks for reporting. Will add a meaningful error message to code generator.
