### ISSUE TITLE
Exception in generating swift file

### ISSUE THREAD

**Issue by xueminlee** [mzaks/FlatBuffersSwift#86]
Hi there, I follow the instructions in the main page to generate a swift file, however I got the ERROR like blew. Anyone could help? thanks.

bogon:FlatBuffersSwift-master-2$ java -jar fbsCG.jar -fbs FlatBuffersSwiftTests/contacts.fbs -out FlatBuffersSwiftTests/contacts_fb_.swift -lang swift -lib import
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 3 more

**Comment by mzaks** [comment]
I just downloaded the version on master as zip. Unzipped it and run `./generate.sh` generating code went as expected.
Could you please tell. me following parameters of your machine: 
- OS 
- java version 
- is FlatBuffersSwiftTests/contacts.fbs the one included in repo

**Comment by xueminlee** [comment]
Dear maxim ,thanks for your response. I have found the problem due to the jdk version.

Thanks,
Xuemin
